const router = require('express').Router();
const auth = require('../middleware/auth.middleware');
const { createProject, getAllProjects, getProjectById, updateProject, deleteProject, addMember, removeMember } = require('../controllers/project.controller');
router.use(auth);
router.post('/', createProject);
router.get('/', getAllProjects);
router.get('/:id', getProjectById);
router.put('/:id', updateProject);
router.delete('/:id', deleteProject);
router.post('/:id/members', addMember);
router.delete('/:id/members/:userId', removeMember);
module.exports = router;
